// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mortalityhazard_gompertz_cpp
NumericVector mortalityhazard_gompertz_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_gompertz_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_gompertz_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_to_prob_gompertz_cpp
NumericVector mortalityhazard_to_prob_gompertz_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_to_prob_gompertz_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_to_prob_gompertz_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_kannisto_cpp
NumericVector mortalityhazard_kannisto_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_kannisto_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_kannisto_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_to_prob_kannisto_cpp
NumericVector mortalityhazard_to_prob_kannisto_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_to_prob_kannisto_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_to_prob_kannisto_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_lb_cpp
NumericVector mortalityhazard_lb_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_lb_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_lb_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_to_prob_lb_cpp
NumericVector mortalityhazard_to_prob_lb_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_to_prob_lb_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_to_prob_lb_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_logistic_cpp
NumericVector mortalityhazard_logistic_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_logistic_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_logistic_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_to_prob_logistic_cpp
NumericVector mortalityhazard_to_prob_logistic_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_to_prob_logistic_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_to_prob_logistic_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_makeham_cpp
NumericVector mortalityhazard_makeham_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_makeham_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_makeham_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_to_prob_makeham_cpp
NumericVector mortalityhazard_to_prob_makeham_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_to_prob_makeham_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_to_prob_makeham_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_quadratic_cpp
NumericVector mortalityhazard_quadratic_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_quadratic_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_quadratic_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_to_prob_quadratic_cpp
NumericVector mortalityhazard_to_prob_quadratic_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_to_prob_quadratic_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_to_prob_quadratic_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_weibull_cpp
NumericVector mortalityhazard_weibull_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_weibull_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_weibull_cpp(theta, z));
    return __result;
END_RCPP
}
// mortalityhazard_to_prob_weibull_cpp
NumericVector mortalityhazard_to_prob_weibull_cpp(NumericVector theta, NumericVector z);
RcppExport SEXP mortfit_mortalityhazard_to_prob_weibull_cpp(SEXP thetaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    __result = Rcpp::wrap(mortalityhazard_to_prob_weibull_cpp(theta, z));
    return __result;
END_RCPP
}
// rmnom
NumericVector rmnom(SEXP n, SEXP p);
RcppExport SEXP mortfit_rmnom(SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type n(nSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    __result = Rcpp::wrap(rmnom(n, p));
    return __result;
END_RCPP
}
