# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mortalityhazard_beard_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_beard_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_to_prob_beard_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_to_prob_beard_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_beard_binomial_grad_cpp <- function(theta, ages, Dx, Nx) {
    .Call('mortfit_mortalityhazard_beard_binomial_grad_cpp', PACKAGE = 'mortfit', theta, ages, Dx, Nx)
}

mortalityhazard_gompertz_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_gompertz_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_to_prob_gompertz_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_to_prob_gompertz_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_gompertz_binomial_grad_cpp <- function(theta, ages, Dx, Nx) {
    .Call('mortfit_mortalityhazard_gompertz_binomial_grad_cpp', PACKAGE = 'mortfit', theta, ages, Dx, Nx)
}

mortalityhazard_kannisto_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_kannisto_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_to_prob_kannisto_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_to_prob_kannisto_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_kannisto_binomial_grad_cpp <- function(theta, ages, Dx, Nx) {
    .Call('mortfit_mortalityhazard_kannisto_binomial_grad_cpp', PACKAGE = 'mortfit', theta, ages, Dx, Nx)
}

mortalityhazard_lb_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_lb_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_to_prob_lb_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_to_prob_lb_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_lb_binomial_grad_cpp <- function(theta, ages, Dx, Nx) {
    .Call('mortfit_mortalityhazard_lb_binomial_grad_cpp', PACKAGE = 'mortfit', theta, ages, Dx, Nx)
}

mortalityhazard_logistic_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_logistic_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_to_prob_logistic_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_to_prob_logistic_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_logistic_binomial_grad_cpp <- function(theta, ages, Dx, Nx) {
    .Call('mortfit_mortalityhazard_logistic_binomial_grad_cpp', PACKAGE = 'mortfit', theta, ages, Dx, Nx)
}

mortalityhazard_makeham_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_makeham_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_to_prob_makeham_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_to_prob_makeham_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_makeham_binomial_grad_cpp <- function(theta, ages, Dx, Nx) {
    .Call('mortfit_mortalityhazard_makeham_binomial_grad_cpp', PACKAGE = 'mortfit', theta, ages, Dx, Nx)
}

mortalityhazard_quadratic_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_quadratic_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_to_prob_quadratic_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_to_prob_quadratic_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_quadratic_binomial_grad_cpp <- function(theta, ages, Dx, Nx) {
    .Call('mortfit_mortalityhazard_quadratic_binomial_grad_cpp', PACKAGE = 'mortfit', theta, ages, Dx, Nx)
}

mortalityhazard_weibull_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_weibull_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_to_prob_weibull_cpp <- function(theta, z) {
    .Call('mortfit_mortalityhazard_to_prob_weibull_cpp', PACKAGE = 'mortfit', theta, z)
}

mortalityhazard_weibull_binomial_grad_cpp <- function(theta, ages, Dx, Nx) {
    .Call('mortfit_mortalityhazard_weibull_binomial_grad_cpp', PACKAGE = 'mortfit', theta, ages, Dx, Nx)
}

rmnom_cpp <- function(n, p) {
    .Call('mortfit_rmnom_cpp', PACKAGE = 'mortfit', n, p)
}

